### ISSUE TITLE
Numerous issues with material

### ISSUE THREAD

**Issue by kphillpotts** [XamarinUniversity/UWP101#1]
From a discussion over at https://forums.xamarin.com/discussion/comment/353830 
DaveCarson pointed out some issues with the material:

> Slide 16 (Load State) finishes with an instruction in point 4 to add an 'if statement' to tests for the PreviousExecutionState but does not say what to place inside it.

> Slide 17 (Save State) appears to have the same point 4 as the previous slide along with the missing point 5

> I also noticed that on slide 27 the video goes blank for 20 seconds at 4:36 - not long but the instructor is discussing what he thinks is being displayed and we never get to see it.

**Comment by patridge** [comment]
Sorry for the delay in replying, Kym. Thanks for filing this issue when you did. Unfortunately, these repos are no longer being maintained, so this issue will be closed.
